# Generated by Django 3.0.1 on 2020-01-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('accounts', '0002_profile_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='universities.University'),
        ),
    ]
