# Generated by Django 3.0.1 on 2020-01-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200131_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/', upload_to='static/avatars'),
        ),
    ]
