# Generated by Django 3.0.1 on 2020-01-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='latitude',
            new_name='lattitude',
        ),
    ]
