# Generated by Django 3.0.1 on 2019-12-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_profile_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('sale_price', models.IntegerField(verbose_name='Sale Price')),
                ('price_on_book', models.IntegerField(verbose_name='Price on Book')),
                ('is_new', models.BooleanField(choices=[(True, 'نو'), (False, 'دسته دوم')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
