# Generated by Django 3.0.1 on 2019-12-30 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 6, 0, 49, 77345, tzinfo=utc)),
        ),
    ]
