# Generated by Django 3.0.1 on 2019-12-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_at',
        ),
    ]
