# Generated by Django 3.0.1 on 2020-01-29 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('sale_price', models.IntegerField(verbose_name='Sale Price')),
                ('price_on_book', models.IntegerField(verbose_name='Price on Book')),
                ('is_new', models.BooleanField(choices=[(True, 'نو'), (False, 'دسته دوم')])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 19, 8, 53, 20836, tzinfo=utc))),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 19, 8, 53, 20864, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
